# This file contains configuration and specifics for the local development environment.

general_settings:
  output_directory: "data/raw_json/"

db_settings:
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "stock_data_dev"
  DB_USER: "postgres"

